In [15]:
import pandas as pd 
import numpy as np 
train=pd.read_csv("E:\\Acods pandas\\Machine learning\\ML Projects Set-1 Data Sets\\Black Friday Sales Data Set\\train.csv")
test=pd.read_csv("E:\\Acods pandas\\Machine learning\\ML Projects Set-1 Data Sets\\Black Friday Sales Data Set\\test.csv")



In [16]:
train.head(2)

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200

In [17]:
test.head(2)

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000004  P00128942      M  46-50           7             B   
1  1000009  P00113442      M  26-35          17             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               1                   1   
1                          0               0                   3   

   Product_Category_2  Product_Category_3  
0                11.0                 NaN  
1                 5.0                 NaN

In [18]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


In [19]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     233599 non-null  int64  
 1   Product_ID                  233599 non-null  object 
 2   Gender                      233599 non-null  object 
 3   Age                         233599 non-null  object 
 4   Occupation                  233599 non-null  int64  
 5   City_Category               233599 non-null  object 
 6   Stay_In_Current_City_Years  233599 non-null  object 
 7   Marital_Status              233599 non-null  int64  
 8   Product_Category_1          233599 non-null  int64  
 9   Product_Category_2          161255 non-null  float64
 10  Product_Category_3          71037 non-null   float64
dtypes: float64(2), int64(4), object(5)
memory usage: 19.6+ MB


In [20]:
train.describe()

User_ID     Occupation  Marital_Status  Product_Category_1  \
count  5.500680e+05  550068.000000   550068.000000       550068.000000   
mean   1.003029e+06       8.076707        0.409653            5.404270   
std    1.727592e+03       6.522660        0.491770            3.936211   
min    1.000001e+06       0.000000        0.000000            1.000000   
25%    1.001516e+06       2.000000        0.000000            1.000000   
50%    1.003077e+06       7.000000        0.000000            5.000000   
75%    1.004478e+06      14.000000        1.000000            8.000000   
max    1.006040e+06      20.000000        1.000000           20.000000   

       Product_Category_2  Product_Category_3       Purchase  
count       376430.000000       166821.000000  550068.000000  
mean             9.842329           12.668243    9263.968713  
std              5.086590            4.125338    5023.065394  
min              2.000000            3.000000      12.000000  
25%              5.000000            9.000000    5823.000000  
50%              9.000000           14.000000    8047.000000  
75%             15.000000           16.000000   12054.000000  
max             18.000000           18.000000   23961.000000

In [21]:
train.isnull().sum()


User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [22]:
test.isnull().sum()


User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2             72344
Product_Category_3            162562
dtype: int64

In [24]:
len(train['User_ID'].unique())

5891

In [26]:
len(train['Product_ID'].unique())

3631

In [27]:
len(test['User_ID'].unique())

5891

In [28]:
len(test['Product_ID'].unique())

3491

In [30]:
train['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [31]:
train['Occupation'].unique()

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6], dtype=int64)

In [32]:
train['City_Category'].unique()

array(['A', 'C', 'B'], dtype=object)

In [33]:
train['Stay_In_Current_City_Years'].unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

In [34]:
train['Product_Category_1'].unique()

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9, 20, 19], dtype=int64)

In [35]:
train['Product_Category_2'].unique()


array([nan,  6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9.,
       10., 17., 13.,  7., 18.])

In [36]:
train['Product_Category_3'].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [39]:
from sklearn.preprocessing import LabelEncoder

train['User_ID']=train['User_ID']-1000000
test['User_ID']=test['User_ID']-1000000

enc=LabelEncoder()
train['User_ID']=enc.fit_transform(train['User_ID'])
test['User_ID']=enc.fit_transform(test['User_ID'])


In [47]:
from sklearn.preprocessing import StandardScaler
import numpy as np

train['Product_ID']=train['Product_ID'].str.replace('P00','')
test['Product_ID']=test['Product_ID'].str.replace('P00','')

scaler=StandardScaler()
train['Product_ID']=enc.fit_transform(train['Product_ID'].values.reshape(-1,1))
test['Product_ID']=enc.fit_transform(test['Product_ID'].values.reshape(-1,1))



C:\Users\Devang Shah\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Devang Shah\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [48]:
len(test['User_ID'].unique())

5891

In [49]:
len(train['User_ID'].unique())

5891

In [50]:
train.head(2)


User_ID  Product_ID Gender   Age  Occupation City_Category  \
0        0         672      F  0-17          10             A   
1        0        2376      F  0-17          10             A   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200

In [51]:
category_column=['Gender','City_Category']
Num_column=['Age','Occupation','Stay_In_Current_City_Years','Product_Category_1','Product_Category_2','Product_Category_3']

In [52]:
#fill missing values with 0
train=train.fillna(0)
test=test.fillna(0)

In [54]:
train.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [55]:
test.isnull().sum()


User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
dtype: int64

In [59]:
# modify age column
train['Age']=train['Age'].map({'0-17':15,
                             '18-25':21,
                             '26-35':30,
                             '36-45':40,
                             '46-50':48,
                             '50-55':53,
                             '55+':60})
test['Age']=test['Age'].map({'0-17':15,
                             '18-25':21,
                             '26-35':30,
                             '36-45':40,
                             '46-50':48,
                             '50-55':53,
                             '55+':60})

In [61]:
# modify stay in couurent city of year
train['Stay_In_Current_City_Years']=train['Stay_In_Current_City_Years'].map({'0':0,
                                                                            '1':1,
                                                                            '2':2,
                                                                            '3':3,
                                                                            '4':4})
test['Stay_In_Current_City_Years']=test['Stay_In_Current_City_Years'].map({'0':0,
                                                                            '1':1,
                                                                            '2':2,
                                                                            '3':3,
                                                                            '4':4})

In [66]:
# Encode catagorial column 
encoder=LabelEncoder()

for col in category_column:
     train[col]=encoder.fit_transform(train[col])
     test[col]=encoder.fit_transform(test[col])
     

In [67]:
# Scale numeric column
scaler=StandardScaler()
train[col]=enc.fit_transform(train[col].values.reshape(-1,1))
test[col]=enc.fit_transform(test[col].values.reshape(-1,1))


C:\Users\Devang Shah\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Devang Shah\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [68]:
train.head()

User_ID  Product_ID  Gender   Age  Occupation  City_Category  \
0        0         672       0  15.0          10              0   
1        0        2376       0  15.0          10              0   
2        0         852       0  15.0          10              0   
3        0         828       0  15.0          10              0   
4        1        2734       1  60.0          16              2   

   Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                         2.0               0                   3   
1                         2.0               0                   1   
2                         2.0               0                  12   
3                         2.0               0                  12   
4                         NaN               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 0.0                 0.0      8370  
1                 6.0                14.0     15200  
2                 0.0                 0.0      1422  
3                14.0                 0.0      1057  
4                 0.0                 0.0      7969

In [79]:
# start training algoridham
from sklearn.model_selection import train_test_split


X=train.drop(['Purchase'],axis=1)
y=train[['Purchase']]
X_test=test
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.20,random_state=42,shuffle=True)


In [82]:
# validating the model
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error



Xgb_reg=XGBRegressor(learning_rate=1.0,max_depth=6,min_child_weight=40,seed=0)
Xgb_reg.fit(X_train,y_train)
y_pred=Xgb_reg.predict(X_val)
rmsc=np.sqrt(mean_squared_error(y_pred,y_val))
print (Xgb_reg,rmsc)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=1.0, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=40, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...) 2624.4305557652447


In [84]:
# training using entire data to improve accuracy
Xgb_reg.fit(X,y)
predict=Xgb_reg.predict(X_test)



In [85]:
predict

array([14576.755 , 10513.437 ,  6263.7427, ...,  9551.879 , 19686.9   ,
       -2036.9541], dtype=float32)